TEST_USER_GOOGLE_ID1 = 'default_google_id1'
TEST_USER_GOOGLE_ID2 = 'default_google_id2'
TEST_USER_FACEBOOK_ID1 = 'default_facebook_id1'
TEST_USER_FACEBOOK_ID2 = 'default_facebook_id2'
TEST_APP_SETTING = 'config.TestingConfig'
